### ISSUE TITLE
ERROR: Invalid client.

### ISSUE THREAD

**Issue by beshoo1** [spaze/oprah-proxy#10]
It seem there is a problem with client API , please advice
```

root@server [/root/download]# /usr/local/bin/python3.5 ./proxy.py
++++++++++++++++++++++++++=======================~~~~~~~::::
,..,,,.,,...,,,.,,,,,,,,,,............,.....,.,,::::~~======
,,,,,:,,,,,,,,,,,,,,                    ,.,,,,,,,,,,,,,....~
~~~~~~~:::::::::::::  YOU GET A PROXY!  ,,,,,,,,,,,,,,,,,:~=
~~===~~~~::::::::::.                    ,,,,,,,,,,,,,,,~~~:~
::~:::::::::::::::,,...,~=::~=~:.....,,,,,,,,,,,,,,,:~:~:,::
??+=..,++++++++++=.....:===I+~=~....,,~~=~~~~~~~:~====~,,::~
::~....,...............~=~~~~:=~,...,.~~~======~==++=~:====+
::~...,:,,,,,,,,.......:==~+=:~:,.....,,,,,,,~~~====~,,,,,,,
:::~~~:,::,,::::,......+~~===~:,.....,,,,,,~~~~~==~,,,,....,
~:~:,,,,,:::::,..........~~::~,:....:~~~~~::::~:::::,,,,,,,,
~...~~~,,::~~::~:........~~~:~::.:,,:~::::::::::::::::::::::
+..???+?~,::::::::::::~:~::~~~:~::::::::::::::::~~=~~~~~~~~=
...?????+?,.:::::::::::~~:~~::~:::::::::::::::,~++++++++++++
?=??????+??~,::::::::~~~~~~~~~~::::::::::::::,=+++++++++++++
????????????::::::,::~~~~~~~~~~:::::::::::::,+++++++++++++++
??+??????????:,,::,:::~~~~~~~:::::::::::::,+++++++++++++++++
??????????????+,,,,:::~~,~~~~~:::=,:::::,?+?++++++++++++++++
????????????????+,:::~~:,~~~~~~~~:~::::=+??+?++?++++++++++++
??????????????????:::~~~~~~~~~~~:::::::???????++++++++++++++
??????????????????=:::~~~~~~~~~::::::::+??????+++++?+?++++++
=+==+====++++++++==:::~:,~~~~~:::,::::~====~~::::,,...,:~~=+
++++++++++++===++++::~:~~~~~~::::~::::=+++++++++++++========
=====+++++=====++++:~:~~~~~~::::::::::~++===================
+++==+======+++                           ==================
~~~~==========~  EVERYBODY GETS A PROXY!  ~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~===~                           ~~~~~~~~~~~~~~~~~~
=============++===:::::::::::::::::::::~~~~~~~~~~~~~~~~~~~:~
https://github.com/spaze/oprah-proxy :::==~=~~~~~~~~=~~~~~~~
DEBUG: Call register_subscriber
DEBUG: Your SurfEasy email: 8810f225-6f8c-4ec0-9dab-af49d8a4d6e5@mailinator.com
DEBUG: Your SurfEasy password: b7966a69-f46b-4a9d-af78-33c2ac96b930
DEBUG: Your SurfEasy password hash: 9E8473BD11DB7FC2B8C751EB42683D5AB60A1E4C
DEBUG: Your mailbox: https://mailinator.com/inbox2.jsp?public_to=8810f225-6f8c-4ec0-9dab-af49d8a4d6e5
DEBUG: These are not the credentials you are looking for (you won't probably need these, ever)
ERROR: Invalid client.

```

**Comment by spaze** [comment]
Thanks @beshoo1! I've now updated the `SE-Client-Type` and `SE-Client-API-Key` request headers with respective values from current stable Opera and it should fly again. Let me know if that's not the case.

**Comment by beshoo1** [comment]
it seems Opera change how it works ! i can not find the SE-Client-Type and SE-Client-API-Key!
and thy change it each day !

Please Advice

**Comment by beshoo1** [comment]
Strange !

`you_get_a_proxy = OprahProxy('se0310', 'AE4CA57D1E3C0E6711C53416BFA0988F08D41B428D26D053A4C46EC72A79B9E7')
`

```
https://github.com/spaze/oprah-proxy :::==~=~~~~~~~~=~~~~~~~
DEBUG: Call register_subscriber
DEBUG: Your SurfEasy email: f89778b5-4b58-47f3-8c7f-339f3d704c6b@mailinator.com
DEBUG: Your SurfEasy password: dfca46ef-ecb7-4fa6-84d1-b9129ff8a2c4
DEBUG: Your SurfEasy password hash: 2C8DBC26C887751164959F6712523BF5244B16AE
DEBUG: Your mailbox: https://mailinator.com/inbox2.jsp?public_to=f89778b5-4b58-47f3-8c7f-339f3d704c6b
DEBUG: These are not the credentials you are looking for (you won't probably need these, ever)
ERROR: Invalid client.

```

**Comment by spaze** [comment]
Please pull in the newest changes, https://github.com/spaze/oprah-proxy/commit/e39fdae7a283165d5ab097c7226651f71300b8c0 has fixed the latest *Invalid client* error.

**Comment by beshoo1** [comment]
@spaze  thank you very much , its work just fine.
But i like to ask , can we automated geting SE-Client-Type and SE-Client-API-Key ?via installing opera on linux ?

**Comment by spaze** [comment]
Maybe. You'd need to do at least three things automagically everytime you'd need the values:

1. install Opera, or reset the user profile
2. enable the VPN feature
3. MitM the connection to SurfEasy API servers

But as you can see in https://github.com/spaze/oprah-proxy/commit/e39fdae7a283165d5ab097c7226651f71300b8c0 the problem was not in wrong type and value

**Comment by beshoo1** [comment]
While i am trying to understand VPN android app of opera , by reverse engineering the APK file . i found this values 
'se0307', '2D67631A124F7AE10629ACA9ACA5AB21D67D30BDF6CF11C0B78735527FDF4DCA'

Which i believe it's hard to be changed since it is apk and hard coded .BTW it is worked just fine !

Any way , i am planing to mimic the connection the the real VPN , it seem same ip address are involved , thy use OpenVPN to connect to the servers.

If anyone like to help , it will be wonderful.
iam searching for the .ovpn file to connect to operaVPN server ,

if any one intrested , reverse engineering the opera APK file .
and start digging :)

**Comment by beshoo1** [comment]
here is some goodies
```
# Enables connection to GUI
management /data/user/0/com.opera.vpn/cache/mgmtsocket unix
management-client
management-query-passwords
management-hold

# Log window is better readable this way
suppress-timestamps
client
verb 3
connect-retry-max 1
resolv-retry 60
dev tun
auth-user-pass
<ca>
-----BEGIN CERTIFICATE-----
MIICbjCCAdegAwIBAgIJALpa3K/RGz7TMA0GCSqGSIb3DQEBBQUAMC8xCzAJBgNV
BAYTAkNBMQswCQYDVQQIEwJPTjETMBEGA1UEAxMKb3BlbnZwbi1jYTAeFw0xMjA4
MjQxNDQxNDVaFw0yMjA4MjIxNDQxNDVaMC8xCzAJBgNVBAYTAkNBMQswCQYDVQQI
EwJPTjETMBEGA1UEAxMKb3BlbnZwbi1jYTCBnzANBgkqhkiG9w0BAQEFAAOBjQAw
gYkCgYEAsFp/304CrPQsoCwEZjTgxH0L8bDfTLvouIc2aGxg8SdhHspA7Gl8pEri
+NjpDV8Z1zwH7vbxMFbV4e9XNU/3OSEO+IcwOf4U376bKMmv7jRtGydo6sCN7vxK
npMhQ8gT+oViVfkZj2rj7XXXHLJBWnIDy7yfI+we3XBM+Izz3xsCAwEAAaOBkTCB
jjAdBgNVHQ4EFgQUPOII5Sm8xvtWnRvlWvXFnUkOMyUwXwYDVR0jBFgwVoAUPOII
5Sm8xvtWnRvlWvXFnUkOMyWhM6QxMC8xCzAJBgNVBAYTAkNBMQswCQYDVQQIEwJP
TjETMBEGA1UEAxMKb3BlbnZwbi1jYYIJALpa3K/RGz7TMAwGA1UdEwQFMAMBAf8w
DQYJKoZIhvcNAQEFBQADgYEAG0hBjHvj5JSm39QrjjKgGDnchsHHV0ox1cPyWp+Z
v4iOjjWigz2jtnl1OetoZvJBOkgwf+r9yCU0/s9gYA8tjVYa2RKXf5DEivdLog4c
3eDsGXFuQm1YhTmdTcjiFs/0SYcbzP5AbNmTCv8KEaIaE6WGpzPKjccH7rd8Q2mk
/DM=
-----END CERTIFICATE-----

</ca>
comp-lzo
nobind
# Use system proxy setting
management-query-proxy
# Custom configuration options
# You are on your on own here :)
<connection>
remote 185.137.17.25
proto udp
port 1194
</connection>

<connection>
remote 185.137.17.25
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.17.25
proto udp
port 53
</connection>

<connection>
remote 185.137.17.22
proto udp
port 1194
</connection>

<connection>
remote 185.137.17.22
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.17.22
proto udp
port 53
</connection>

<connection>
remote 185.137.19.205
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.205
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.205
proto udp
port 53
</connection>

<connection>
remote 185.137.19.201
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.201
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.201
proto udp
port 53
</connection>

<connection>
remote 185.137.19.211
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.211
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.211
proto udp
port 53
</connection>

<connection>
remote 185.137.19.203
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.203
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.203
proto udp
port 53
</connection>

<connection>
remote 185.137.19.221
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.221
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.221
proto udp
port 53
</connection>

<connection>
remote 185.137.19.214
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.214
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.214
proto udp
port 53
</connection>

<connection>
remote 185.137.19.220
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.220
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.220
proto udp
port 53
</connection>

<connection>
remote 185.137.19.223
proto udp
port 1194
</connection>

<connection>
remote 185.137.19.223
proto tcp-client
port 443
</connection>

<connection>
remote 185.137.19.223
proto udp
port 53
</connection>

# These Options were found in the config file do not map to config settings:
ns-cert-type server 
ping 10 
ping-restart 15 
```

**Comment by beshoo1** [comment]
i can not find auth-user-pass
i tide the returned username and password from the python script but it dos not worked :)

**Comment by IgorOne** [comment]
@beshoo1  how is your progress in this?
I managed to find similar values in the OperaVPN App for iOS (I didn't reverse-engineer the executable, I managed to find all the connection properties in the Cache files of the app)

What script did you try to use to connect to the OpenVPN Server ?

**Comment by beshoo1** [comment]
Well i found it is dame as proxy connection same ip address same ports but
what i did not foumd the password for the openvpn.

**Comment by IgorOne** [comment]
I don't believe that the connection is established with a password, but with a certificate - does OpenVPN allow this ?
See here:

[058BC9CA-45C1-43D0-9FED-FB745CB89CB5.txt](https://github.com/spaze/oprah-proxy/files/810735/058BC9CA-45C1-43D0-9FED-FB745CB89CB5.txt)

That's in JSON - there are keys called "cert_password" and "device_p12" - I assume there is a certificate(??) which allows the secure connection. But I'm not sure. The file appears to contain the request/ response to the server as far as I understand.

I hope someone could get a hang on this.

**Comment by h3298** [comment]
I understand what you are trying to do; there seems to be some degree of commonality or compatibility between the two services.  This could be relevant also:

https://chrome.google.com/webstore/detail/surfeasy-vpn-security-pri/odiddbcijempnhhobijfbggjogofdlgl

One difference in v4 Opera proxy, the certificates are much bigger than the Android one you reversed.  So the method could have change.  See for example in opera://net-internals/#events
t=45075 [st= 0] +**CERT_VERIFIER_JOB**  [dt=30]

For the OVPN config file, "management" directives are only valid on linux, so comment them out with "#" on other platforms.  Also, you could possibly replace the server connections with the Opera proxy servers, e.g.

remote 162.248.180.144 443
remote 162.248.178.119 443
remote 69.90.50.189 443
remote 209.15.26.178 443
remote 162.248.180.127 443

I believe the <connection> </connection> tags are deprecated and no longer necessary

The certs might be used like this:
https://www.brainfart.sg/index.php/2012/05/embedding-certificate-into-openvpn-config/

**Comment by h3298** [comment]
re "It seem there is a problem with client API , please advice
ERROR: Invalid client."

just for reference, a working version is here: https://github.com/nampud/oprah-proxy

**Comment by h3298** [comment]
Opera just pushed an iOS update called **"Opera VPN gold"** and the free servers immediately quit working after installing.  Android & iOS users with root might want to backup the old VPN client before updating.
