### ISSUE TITLE
CURL Command line + PHP [How To]

### ISSUE THREAD

**Issue by beshoo1** [spaze/oprah-proxy#14]
Since oprah-proxy give you HTTPS proxy, then you can not use php Curl built in CurlLib .
as far as phpCurlLib dos not support HTTPS proxy.

So to make this wroks . just download ,and compile latest Curl Lib , 7.5.1 which finlay it is support HTTPS proxy,

and use shell_exec(curl ..... ) in your php.

`curl --proxy  https://591c63c7564a49341d9e24bdeae6e37d7bae355f:459AECA9145FDE979BF0D2970261BEBB5F3B285D812850A6B9D6C8628B2EDEA7@68.71.55.53:443 --proxy-insecure http://whatismyip.org`

Happy Proxy Time :)

**Comment by spaze** [comment]
Thanks, yay, curl, that's a good news! I've made a note at #4 to update the docs.
