### ISSUE TITLE
A little bit confusing instructions?

### ISSUE THREAD

**Issue by GGGunrunner** [spaze/oprah-proxy#15]
The PAC file uses hardcoded location (DE), if you want to use other location just download the file, change the hostname (available hostnames are {ca,de,us}.opera-proxy.net), change your browser configuration, and you should be ready to go. 

^^^
Just want to clarify it: what does "change your browser configuration" mean?
If I edit pac.js and put US or CA instead of DE, what shall I do next?
Save the edited file locally and point Auto-detect to something like file://..../pac.js  ?

**Comment by spaze** [comment]
Yes.
