### ISSUE TITLE
not working: no proxy auth window in browsers

### ISSUE THREAD

**Issue by MarvinFS** [spaze/oprah-proxy#19]
for some reason it doesn't work.
although script shows me correct credentials such as:

> https://api.surfeasy.com:443 "POST /v2/discover HTTP/1.1" 200 None
> 2017-05-08 00:20:59,564 INFO     Your location is RU/71
> 2017-05-08 00:20:59,564 INFO     Proxy in NL/0 185.137.17.99:443
> 2017-05-08 00:20:59,564 INFO     Proxy in NL/0 185.137.18.106:80
> 2017-05-08 00:20:59,564 INFO     Proxy in NL/0 185.137.18.182:8181
> 2017-05-08 00:20:59,564 INFO     Proxy in NL/0 185.137.18.120:22
> 2017-05-08 00:20:59,565 INFO     Proxy in NL/0 185.137.18.218:443
> 2017-05-08 00:20:59,565 INFO     Proxy in NL/0 185.137.18.84:80
> 2017-05-08 00:20:59,565 INFO     Proxy in NL/0 185.137.17.90:8181
> 2017-05-08 00:20:59,565 INFO     Proxy in NL/0 185.137.18.102:22
> 2017-05-08 00:20:59,565 INFO     Proxy in NL/7 188.166.53.215:443
> 2017-05-08 00:20:59,566 INFO     Proxy in NL/0 185.137.19.126:80
> 2017-05-08 00:20:59,566 DEBUG    10 proxies discovered
> 2017-05-08 00:20:59,566 INFO     Pick a proxy from the list above and use these credentials:
> 2017-05-08 00:20:59,566 INFO     Username: $$$$$$
> 2017-05-08 00:20:59,566 INFO     Password: #########
> 2017-05-08 00:20:59,566 INFO     HTTP header Proxy-Authorization: Basic ####$$$$!!!!!!!

in a browsers none off the proxies listed above work directly with ip:port designation - empty response. when using pac.js file the best i've managed to achieve is: "Authentication credentials required" message in browser windows. no proxy basic auth windows appears as it should with common proxy solutions with manual auth. my local proxies with basic auth are working as expected showing an auth window in all the browsers.
tried firefox, ie11, chromium 60. nothing. one time the proxy auth windows appeared in firefox, but after restart it's gone again. 
in opera's native mode everything is working though.
i've tried cascading proxy with manual basic auth (ccproxy) - also doesn't work.
any suggestions?

**Comment by spaze** [comment]
Sorry, the discover call is known to be broken, see #18, I've now removed the IP address listing. Only the hostname is now shown.

The pac.js provided in this repo triggers the auth window with no modification. I'd suggest not to rely on IP addresses.
