### ISSUE TITLE
Use /v4 API

### ISSUE THREAD

**Issue by spaze** [spaze/oprah-proxy#21]
Opera 45.0.2552.812 has switched to v4 API. That API uses HTTP Digest Authentication instead of `SE-...` HTTP headers.

```
POST /v4/register_subscriber HTTP/1.1
Host: api.surfeasy.com
Connection: keep-alive
Content-Length: 128
Accept: application/json
SE-Client-Version: Stable 45.0.2552.812
SE-Operating-System: Windows
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 OPR/45.0.2552.812
Accept-Encoding: gzip, deflate, br

HTTP/1.1 401 Unauthorized
Server: nginx/1.12.0
Date: Thu, 18 May 2017 20:32:04 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Status: 401 Unauthorized
WWW-Authenticate: Digest realm="ApiDigest", qop="auth", algorithm=SHA-256, nonce="MTQ5NTEzOTUyNDozNDEyMjA0OWY0ZjE4ZDgwZDFjOGI5M2ZiNmUyMzYyMWI4Y2NiYTNiMDEwZTdmNzU0NzY2ZTNjOTA2NmYwYWM2", opaque="a6feff632d495616728c8ef3532064ca457e3d0badcfa2db349a0433dcc4520f"
X-UA-Compatible: IE=Edge,chrome=1
Cache-Control: no-cache
X-Request-Id: 66c73f05d6950077cfd83b58fc9f498e
X-Runtime: 0.009371
X-Rack-Cache: invalidate, pass

POST /v4/register_subscriber HTTP/1.1
Host: api.surfeasy.com
Connection: keep-alive
Content-Length: 128
Authorization: Digest username="se0316", realm="ApiDigest", nonce="MTQ5NTEzOTUyNDozNDEyMjA0OWY0ZjE4ZDgwZDFjOGI5M2ZiNmUyMzYyMWI4Y2NiYTNiMDEwZTdmNzU0NzY2ZTNjOTA2NmYwYWM2", uri="/v4/register_subscriber", algorithm=SHA-256, response="ff7f495b6dd7c0b53119f3f92e6f3dbb7607d6a4d0441ec77359437e8b958ee2", opaque="a6feff632d495616728c8ef3532064ca457e3d0badcfa2db349a0433dcc4520f", qop=auth, nc=00000001, cnonce="d186e18e5c7172fa"
Accept: application/json
SE-Client-Version: Stable 45.0.2552.812
SE-Operating-System: Windows
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 OPR/45.0.2552.812
Accept-Encoding: gzip, deflate, br
```

To calculate correct `response` the password is needed, according to [RFC 7616](https://tools.ietf.org/html/rfc7616#section-3.4.1):

```
3.4.2.  A1
   If the algorithm parameter's value is "<algorithm>", e.g., "SHA-256",
   then A1 is:
         A1       = unq(username) ":" unq(realm) ":" passwd
   where
         passwd   = < user's password >
```

**Comment by lonlyman** [comment]
I have 44.0.2510.1449 (PGO) and i can not find how its works ! VPN just works fine !

**Comment by tugrul** [comment]
https://chrome.google.com/webstore/detail/surfeasy-vpn-security-pri/odiddbcijempnhhobijfbggjogofdlgl

Looks like use same API but v3.

JavaScript code is not obfuscated and easy to understand.

**Comment by linadlight** [comment]
```
  static recaptcha() {
    return [
      'iframe', {
        'frameborder': '0',
        'src': 'https://api.surfeasy.com/captcha',<==============================
        'scrolling': 'yes',
        'id': 'captcha',
        'style': 'width: 290px; border-style: none;'
      }
    ];
  }
```

**Comment by spaze** [comment]
@tugrul Thanks, I've used the extension as a reference when researching how Opera works. It's a different product and a paid service, though.

**Comment by linadlight** [comment]
> It's a different product and a paid service, though.
They provide 500Mb free 

but since captcha :(

**Comment by GGGunrunner** [comment]
Yep, resistance is useless, but they keep on trying.

2017-05-29 09:17:38,345 DEBUG    "POST /v2/register_subscriber HTTP/1.1" 200 None
2017-05-29 09:17:38,348 DEBUG    ERROR: Unknown or invalid client type/product code provided.

Is there any fresh fix for that? Muchos gracias!

**Comment by nampud** [comment]
se0316 is the client id/username, 94938A583190AF928BC4FA2279DC10AE8FABB5E9E21826C9092B404D24B949A0 is the password. Dumped from RAM. v4 api is the same as v2 (at least for the api calls this script uses), but with digest auth. I have a working oprahProxy script, but it's ugly, as I had to copy the HTTPDigestAuth code from the requests library because I had to add a few lines for SHA-256 algorithm support.

**Comment by instagramlover** [comment]
@nampud nice work , can you share how you dump the RAM ? and may you share the python script , i will work on it to make it robust !

**Comment by nampud** [comment]
Sure, it's on my fork https://github.com/nampud/oprah-proxy

**Comment by instagramlover** [comment]
@nampud how you dumped the ram ? may you share the method!

**Comment by instagramlover** [comment]
@nampud  did you note : se0309 is available in the dump ! but i can not found the password :)

**Comment by nampud** [comment]
Sure, it's on my fork https://github.com/nampud/oprah-proxy
According to the digest auth specs, Opera must create the following string to create the hash necessary for digest auth: se0316:ApiDigest:passwordhere, so I opened Process Hacker and Opera, connected to VPN, and searched for the known part (se0316:ApiDigest:), and it gave me the full string including password. The string is not always there, but sometimes it is, it may help to switch VPN on and off multiple times before dumping. The password is stored obfuscated in the opera_browser.dll, so it's hard to get it directly from there.

**Comment by instagramlover** [comment]
i am doing the same , not even once this password appear :) lol
@nampud i note sometimes the generated password form oprah-proxy.py is not what API care about , try to change some characters from the password but keep the linth.

the connection will pass throw ! but the username you can not do such thing with,

did  you note such !

**Comment by kekukui** [comment]
**@instagramlover** _"may you share the python script , i will work on it to make it robust!"_

script should be used in a browser extension so proxy server can be changed through a menubar button like this: https://addons.mozilla.org/en-US/firefox/addon/pac-reloader/

**Comment by hbakhtiyor** [comment]
@nampud none of the client's types/keys work

**Comment by nampud** [comment]
@hbakhtiyor It still seems to work for me, and it looks like the latest Opera still uses the same keys. Download my forked version ( https://github.com/nampud/oprah-proxy ), and if it doesn't work, please post the output.

**Comment by hbakhtiyor** [comment]
@nampud yeah, your forked version works, @spaze  why still not merge to your repo?
 

something warning:
```
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

**Comment by spaze** [comment]
@hbakhtiyor I'll happily merge a sensible pull request once there's any

**Comment by alaadiab** [comment]
@hbakhtiyor Opera changed to a new level (api.sec-tunnel.com) which is now unbeatable i think !

**Comment by spaze** [comment]
Opera is making some nice progress, this tool has served it's purpose (to learn new stuff) and as such is now deprecated.
