### ISSUE TITLE
I think it is the time to close this wondeful project

### ISSUE THREAD

**Issue by lonlyman** [spaze/oprah-proxy#22]
Nothing is working , and if we let this project available we will waste users time, @spaze list that the python file is working while it is not !

User may spend time to install python 3 and at the end nothing is working !

Please just put a statement that the file is no longer works unless we found the password which is almost impossible !

**Comment by spaze** [comment]
There's a disclaimer for people like you who'd like to base their businesses on this.
https://github.com/spaze/oprah-proxy/commit/965698fc5397dc0743cf268411f99d7122a3555a

**Comment by spaze** [comment]
I've deleted the API key, https://github.com/spaze/oprah-proxy/commit/98c852d39283d77d672b29596973340a79bf217c. Sorry everyone for enabling shady businesses like @lonlyman's instaRanker. I should not have included it from the beginning.
