### ISSUE TITLE
Changed again

### ISSUE THREAD

**Issue by GGGunrunner** [spaze/oprah-proxy#23]
Yep, resistance is useless, but they keep on trying.

2017-05-27 09:27:38,345 DEBUG    "POST /v2/register_subscriber HTTP/1.1" 200 None
2017-05-27 09:27:38,348 DEBUG    ERROR: Unknown or invalid client type/product code provided.

Is there any fresh fix for that? Muchos gracias!

**Comment by spaze** [comment]
No, sorry. Get the API key yourself and edit the script, then it should work fine with v2 API.

**Comment by GGGunrunner** [comment]
So I assume this project is officially dead now? :-(

**Comment by spaze** [comment]
It's not, the API client works, if you provide the keys. I stopped providing them, sorry. It was a mistake to provide them at all.

**Comment by GGGunrunner** [comment]
Thanks! Is there any tutorial on how to get/generate them?

**Comment by spaze** [comment]
No, it's not. [This](https://github.com/spaze/oprah-proxy/issues/6#issuecomment-240347966) used to work, but not anymore.

You have three options:
1. Ask Opera for the key
2. Reverse engineer Opera
3. Sniff the traffic

Either option you'll go with you'll learn a lot along the way. And that's what's the main purpose of this project and repository. Learn how stuff works.
