### ISSUE TITLE
client_type and client_type

### ISSUE THREAD

**Issue by ganesshkumar** [spaze/oprah-proxy#26]
In the usage 
```
oprahProxy.py <client_type> <client_key>
```
what are these client_type and client_key stand for? Can you add bit more detail on how to obtain those or what are valid client_type?

**Comment by spaze** [comment]
`client_type` is a client id which is different for different versions of Opera browser, `client_key` is the API key which is used for communicating with Surfeasy servers.

I've stopped providing these after I've realized some people were using this tool for commercial purposes (which is fine) to bypass some ToS (not fine), and demanded I provide new type and key whenever the current one stopped working. It's users job now to get the type and key, there are some ideas in #21's comments.

**Comment by hbakhtiyor** [comment]
@spaze any step by step guide how to get the values (client's type & key) from opera?
