### ISSUE TITLE
Dont proxy local addresses [pac.js]

### ISSUE THREAD

**Issue by kekukui** [spaze/oprah-proxy#27]
For https://github.com/spaze/oprah-proxy/blob/master/pac.js
**Sample fixed PAC file**
```
function FindProxyForURL(url, host) {
 
// bypass proxy for local addresses
    if (isPlainHostName(host) ||
        shExpMatch(host, "*.local") ||
        isInNet(dnsResolve(host), "10.0.0.0", "255.0.0.0") ||
        isInNet(dnsResolve(host), "172.16.0.0",  "255.240.0.0") ||
        isInNet(dnsResolve(host), "192.168.0.0",  "255.255.0.0") ||
        isInNet(dnsResolve(host), "127.0.0.0", "255.255.255.0"))
        return "DIRECT";
 
// DEFAULT RULE: All other traffic use this proxy
	return 'HTTPS ca.opera-proxy.net:443';

}
```
__________
**General PAC reference**
https://support.mozilla.org/en-US/kb/advanced-panel-settings-in-firefox#w_connection
https://www.websense.com/content/support/library/web/v76/pac_file_best_practices/PAC_best_pract.aspx
https://www.websense.com/content/support/library/web/v76/pac_file_best_practices/PAC_file_sample.aspx
http://findproxyforurl.com/example-pac-file/

**PAC validator / parser utilities**
https://chentiangemalc.wordpress.com/2013/09/30/pacdbg-custom-proxy-browser-set-proxy-cmd-line-tool/
https://github.com/pacparser/pacparser

**How to use a local PAC file instead of cloud hosted file**
https://www.cisco.com/c/en/us/td/docs/security/web_security/connector/connector3000/PACAP.html#wp1015209

**In-browser PAC editor**
https://addons.mozilla.org/en-US/firefox/addon/pac-reloader

**Comment by spaze** [comment]
Thanks, care to make a pull request for that?
