### ISSUE TITLE
Two ways to use this proxy in Python

### ISSUE THREAD

**Issue by scturtle** [spaze/oprah-proxy#3]
After got the secret sauce:

``` python
basic_auth, proxy, port = get_proxy()
```

I find that one low-level way to use it is:

``` python
req = 'GET {url} HTTP/1.0\nProxy-Authorization: BASIC {basic_auth}\n\n'.format(
    url='http://httpbin.org/ip', basic_auth=basic_auth)
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock = ssl.wrap_socket(sock)
sock.connect((proxy, port))
sock.send(req.encode('ascii'))
print(sock.recv(1024))
sock.close()
```

Another method needs an ugly monkey patch of `HTTPSConnection` to avoid SNI error:

``` python
class PatchedContext:

    def __init__(self, conn):
        conn._check_hostname = False
        conn._context.check_hostname = False
        self.ctx = conn._context

    def __getattr__(self, attr):
        if attr == 'wrap_socket':
            return lambda sock, server_hostname: self.ctx.wrap_socket(sock)
        return getattr(self.ctx, attr)

conn = http.client.HTTPSConnection(proxy, port)
conn._context = PatchedContext(conn)
conn.request("GET", "http://httpbin.org/ip",
             headers={"Proxy-Authorization": "BASIC "+basic_auth})
print(conn.getresponse().read())
```

**Comment by dessant** [comment]
@scturtle, were you able to use it with https sites? `https://httpbin.org/ip` and others result in `500 Internal Server Error`.

**Comment by scturtle** [comment]
@dessant I can use it as plain HTTP/HTTPS proxy now:) See my [gist](https://gist.github.com/scturtle/4f2d95507b2d357f1b17a538a1d36d82).

**Comment by dessant** [comment]
@scturtle oh lovely, thanks for sharing. :trophy:

**Comment by spaze** [comment]
@scturtle Thanks for sharing! Any idea how can I package it with my script together? Or do an update to docs or something?

**Comment by scturtle** [comment]
@spaze Not really. Just share here in case someone needs. Pls feel free to take any part of the code or close this issue.

**Comment by ucupumar** [comment]
Thanks for sharing! If possible, can you do another example but using python requests?

**Comment by 0at** [comment]
I tried the above code changes and still seem to be getting a b'malformed HTTP response "<html>"\n'.  Is there something that I'm missing?

I used the proxy.py script in the gist you made and it seems to work when I do that. So not sure why there would be something specific to doing the monkey patch (I've tested to make sure that the proxy credentials are valid)

**Comment by kapkirl** [comment]
With http resources everything is fine, but with https - `malformed HTTP response "<html>"`
Any ideas how to handle that?
