### ISSUE TITLE
Not a VPN? Really?

### ISSUE THREAD

**Issue by GGGunrunner** [spaze/oprah-proxy#5]
Thanks for creating this script, man!

Can you elaborate on the following: to test your statement that OperaVPN is just a proxy, I ran a quick and dirty gimmick:

Ipad (Jailbroken 8.3)
Kali Linux 
Ettercap, Wireshark.

Did MITM ARP poison on Kali and routed Ipad's traffic to it.

VPN ON:
All visible traffic is between the vpn gate in Germany and ipad's local ip. No other SRC or DST ip's.
Not even dns queries. Launched browsers, messengers, different apps.

VPN OFF:
Direct connections to hundreds of ip's, dns queries to apple servers, TLS etc.
Just as expected.

When VPN is on, a new interface is up:

utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1280
        inet 10.251.17.218 --> 10.251.17.218 netmask 0xffffffff 

From what I see, it talks via ESP (Encapsulating Security Payload) which I'm not familiar with, but I reckon its part of IPSec family?

So please cure my ignorance, what I did wrong? Thanks!

**Comment by spaze** [comment]
@GGGunrunner You did nothing wrong. [Opera VPN for iOS](https://itunes.apple.com/us/app/opera-free-vpn-unlimited-free/id1080756781?mt=8) is a different thing than the "VPN" in Opera the desktop browser, and luckily, it's the real VPN, see my [earlier tweet](https://itunes.apple.com/us/app/opera-free-vpn-unlimited-free/id1080756781?mt=8).

So, Opera VPN for iOS is a real VPN, while "VPN" in Opera browser is just a secure proxy. Yeah, it's a mess.
