### ISSUE TITLE
The script stopped working

### ISSUE THREAD

**Issue by dessant** [spaze/oprah-proxy#6]
The api responds with this error:

```
{'data': {}, 'return_code': {'19': 'Invalid client.'}}
```

**Comment by spaze** [comment]
Thanks, I've updated client type and API key from upstream and it should work again.

**Comment by dessant** [comment]
This gets past the registering api requests, strangely I'm getting 403 when `/v2/discover` is called, the same happens also in the Opera browser though.

```
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

**Comment by dessant** [comment]
> VPN – there are some issues with service availability, so you’ll notice that there is never-ending ‘Connecting’ status displayed. Our developers are already working on it.

https://www.opera.com/blogs/desktop/2016/08/opera-developer-update-41-0-2323-0/

**Comment by dessant** [comment]
@spaze, how did you get `SE-Client-API-Key` btw? :yum: It does not seem to be exposed in net-internals anymore.

**Comment by spaze** [comment]
Interesting, it worked for me yesterday and `/v2/discover` returns list of proxies even today. But Opera the browser was behaving exactly as described in the blog post.

**Comment by spaze** [comment]
@dessant `SE-Client-API-Key` is still visible in [net-internals](opera://net-internals), if you enable _Include the actual bytes sent/received._ at [net-internals#capture](opera://net-internals#capture), then just search for `se-client` in [net-internals#events](opera://net-internals#events), it's in the Source Type = `SOCKET` event. This is how I got all the needed POST data to build this tool in the first place. Wondering when they will strip this too.

**Comment by dessant** [comment]
@spaze, wow that's gorgeous, I was only looking at URL_REQUEST type events, thanks a bunch! Meanwhile the api issues also got solved.

**Comment by dessant** [comment]
@spaze, we could remove our posts. :grin:

**Comment by spaze** [comment]
@dessant Let's leave this here for anybody to learn something new :-) #hack2learn

**Comment by dessant** [comment]
@spaze, it's happening. 😿 

```
SSL_SOCKET_BYTES_SENT
                           --> byte_count = 671
                           --> hex_encoded_bytes =
                             5B 36 37 31 20 62 79 74  65 73 20 77 65 72 65 20   [671 bytes were 
                             73 74 72 69 70 70 65 64  5D                        stripped]
```

**Comment by spaze** [comment]
@dessant At last!
