### ISSUE TITLE
I tried to use the .pac file under MacOS or iOS and it will not ask for credential

### ISSUE THREAD

**Issue by aeroxy** [spaze/oprah-proxy#8]
Hi, I used the .pac file created by myself (try using both the domain and the ip address directly) under MacOS or iOS. There will be no pop up for credential, instead there is just no internet access.

**Comment by spaze** [comment]
Hi, thanks for the report. Doesn't seem like an issue with the Python script or the PAC file hosted in this repository. Please test your PAC file using other browsers and/or OS and if it works there then please ask your OS vendor (or browser or proxy server vendors) for help. I don't provide such support, sorry. Feel free to share your solution with us, though. Thanks!
